name: CD Workflow

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - run: git fetch --tags origin

      - name: Create .env file
        run: |
          echo VITE_DOMAIN=${{ secrets.VITE_DOMAIN }} >> .env
          echo VITE_BACKEND_URL=${{ secrets.VITE_BACKEND_URL }} >> .env

      - name: node v20.x setup
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
